const styles = {
  container: {
    fontFamily: "Arial, sans-serif",
    maxWidth: "600px",
    margin: "0 auto",
    padding: "20px",
    boxSizing: "border-box",
  },
  header: {
    textAlign: "center",
    color: "#333",
    fontSize: "2.5em",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: "2px",
    margin: "20px 0",
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
    fontFamily: "'Roboto', sans-serif",
    background: "linear-gradient(45deg, #0077cc, #00cc99)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  subtitle: {
    fontSize: "1em",
    color: "#666",
    fontStyle: "italic",
    marginBottom: "20px",
    justifyContent: "center",
    display: "flex",
  },
  createTaskCard: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    padding: "16px",
    marginBottom: "20px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  input: {
    padding: "10px",
    fontSize: "16px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    width: "calc(100% - 4px)",
    boxSizing: "border-box",
  },
  button: {
    padding: "10px",
    fontSize: "16px",
    backgroundColor: "#2196F3",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "background-color 0.3s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "5px",
    width: "100%",
  },
  taskCard: {
    backgroundColor: "#fff",
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  taskHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  taskTitle: {
    margin: "0",
    fontSize: "1.2em",
    fontWeight: "bold",
    color: "#333",
  },
  taskDescription: {
    color: "#666",
    marginBottom: "10px",
  },
  deleteButton: {
    backgroundColor: "#f44336",
    color: "white",
    border: "none",
    padding: "5px 10px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.9em",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  completeButton: {
    backgroundColor: "#2196F3",
    color: "white",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.9em",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    transition: "background-color 0.3s",
  },
  errorMessage: {
    color: "red",
    textAlign: "center",
    marginBottom: "10px",
  },
};

export default styles;
