services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    hostname: dynamodb-local
    ports:
      - "${DYNAMODB_LOCAL_HOST_PORT:-18000}:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  instant-payments-js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-payments-js
    ports:
      - "8080:8080"
    environment:
      # Default values for local development
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-8080}
      # AWS environment variables
      AWS_ENDPOINT_URL: http://dynamodb-local:8000
      AWS_REGION: eu-west-1
      # DynamoDB environment variables
      DYNAMODB_CLIENT_TYPE: ${DYNAMODB_CLIENT_TYPE:-high-level}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME:-JS_InstantPayments}
      DYNAMODB_IDEMPOTENCY_TTL_SECONDS: ${DYNAMODB_IDEMPOTENCY_TTL_SECONDS:-2592000}
      DYNAMODB_STREAMS_ITERATOR_TYPE: ${DYNAMODB_STREAMS_ITERATOR_TYPE:-LATEST}
    depends_on:
      - dynamodb-local
    profiles:
      - app

