#
#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  This file is licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License. A copy of
#  the License is located at
#
#  http://aws.amazon.com/apache2.0/
#
#  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the
#  specific language governing permissions and limitations under the License.
#
"""Property-based tests for data models.

This module contains property-based tests using Hypothesis to verify
universal correctness properties of the data model classes.
"""

from decimal import Decimal

from hypothesis import given
from hypothesis import strategies as st

from src.models import CSVRecord


# Feature: dynamodb-csv-bulk-loader, Property 9: Required Fields Present
# For any record generated by the CSV generator, all required fields
# (id, timestamp, category, user_name, email, amount, status, description)
# should be present and non-empty.
@given(
    id=st.text(min_size=1),
    timestamp=st.text(min_size=1),
    category=st.text(min_size=1),
    user_name=st.text(min_size=1),
    email=st.text(min_size=1),
    amount=st.decimals(
        min_value=Decimal("0.01"),
        max_value=Decimal("999999.99"),
        allow_nan=False,
        allow_infinity=False,
        places=2,
    ),
    status=st.text(min_size=1),
    description=st.text(min_size=1),
)
def test_csv_record_required_fields_present(
    id: str,
    timestamp: str,
    category: str,
    user_name: str,
    email: str,
    amount: Decimal,
    status: str,
    description: str,
) -> None:
    """Property test: All required fields must be present and non-empty.

    This test verifies that CSVRecord instances always have all required fields
    present and non-empty, which is critical for data integrity when loading
    into DynamoDB.

    Validates: Requirements 4.3
    """
    # Create a CSVRecord with the generated values
    record = CSVRecord(
        id=id,
        timestamp=timestamp,
        category=category,
        user_name=user_name,
        email=email,
        amount=amount,
        status=status,
        description=description,
    )

    # Verify all fields are present (not None)
    assert record.id is not None, "id field must be present"
    assert record.timestamp is not None, "timestamp field must be present"
    assert record.category is not None, "category field must be present"
    assert record.user_name is not None, "user_name field must be present"
    assert record.email is not None, "email field must be present"
    assert record.amount is not None, "amount field must be present"
    assert record.status is not None, "status field must be present"
    assert record.description is not None, "description field must be present"

    # Verify all string fields are non-empty
    assert len(record.id) > 0, "id field must be non-empty"
    assert len(record.timestamp) > 0, "timestamp field must be non-empty"
    assert len(record.category) > 0, "category field must be non-empty"
    assert len(record.user_name) > 0, "user_name field must be non-empty"
    assert len(record.email) > 0, "email field must be non-empty"
    assert len(record.status) > 0, "status field must be non-empty"
    assert len(record.description) > 0, "description field must be non-empty"

    # Verify amount is a valid positive decimal
    assert isinstance(record.amount, Decimal), "amount must be a Decimal"
    assert record.amount > 0, "amount must be positive"

    # Verify the record can be converted to DynamoDB format
    dynamodb_item = record.to_dynamodb_item()

    # Verify all fields are present in DynamoDB item
    assert "id" in dynamodb_item, "id must be in DynamoDB item"
    assert "timestamp" in dynamodb_item, "timestamp must be in DynamoDB item"
    assert "category" in dynamodb_item, "category must be in DynamoDB item"
    assert "user_name" in dynamodb_item, "user_name must be in DynamoDB item"
    assert "email" in dynamodb_item, "email must be in DynamoDB item"
    assert "amount" in dynamodb_item, "amount must be in DynamoDB item"
    assert "status" in dynamodb_item, "status must be in DynamoDB item"
    assert "description" in dynamodb_item, "description must be in DynamoDB item"

    # Verify all DynamoDB item values are non-empty
    assert len(dynamodb_item["id"]) > 0, "id in DynamoDB item must be non-empty"
    assert len(dynamodb_item["timestamp"]) > 0, "timestamp in DynamoDB item must be non-empty"
    assert len(dynamodb_item["category"]) > 0, "category in DynamoDB item must be non-empty"
    assert len(dynamodb_item["user_name"]) > 0, "user_name in DynamoDB item must be non-empty"
    assert len(dynamodb_item["email"]) > 0, "email in DynamoDB item must be non-empty"
    assert len(dynamodb_item["amount"]) > 0, "amount in DynamoDB item must be non-empty"
    assert len(dynamodb_item["status"]) > 0, "status in DynamoDB item must be non-empty"
    assert len(dynamodb_item["description"]) > 0, "description in DynamoDB item must be non-empty"
